plugins {
    id 'java'
    id 'jacoco'
}

jacoco {
    toolVersion = '0.8.11'
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation platform(project(':bom'))

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    implementation 'org.springframework:spring-webmvc'
    implementation 'org.springframework.data:spring-data-jdbc'

    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    implementation 'javax.annotation:javax.annotation-api'

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'

    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'

    implementation 'com.zaxxer:HikariCP'
    implementation 'org.postgresql:postgresql'

    implementation 'commons-fileupload:commons-fileupload'
    implementation 'commons-io:commons-io'

    implementation 'org.slf4j:slf4j-api'
    runtimeOnly 'ch.qos.logback:logback-classic'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.hamcrest:hamcrest'
    testImplementation 'org.mockito:mockito-junit-jupiter'
    testImplementation 'org.mockito:mockito-inline'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'org.springframework:spring-test'
    testImplementation 'org.slf4j:slf4j-simple'
    testImplementation 'com.h2database:h2'
}

jar {
    enabled = true
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.compilerArgs.add('-parameters')
}

test {
    useJUnitPlatform()
}
